# Generated by Django 5.2.5 on 2025-08-24 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_load_initial_users'),
    ]

    operations = [
    ]
