# Generated by Django 5.2.5 on 2025-08-24 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_force_reset_superuser_password'),
    ]

    operations = [
    ]
