# Generated by Django 5.2.5 on 2025-08-24 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_load_production_users'),
    ]

    operations = [
    ]
