# Generated by Django 5.2.5 on 2025-08-24 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pessoa', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2)),
                ('nome_razao_social', models.CharField(help_text='Nome completo se for PF, Razão Social se for PJ', max_length=150)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('nome_contato', models.CharField(blank=True, help_text='Preencher apenas se for Pessoa Jurídica', max_length=100, null=True)),
                ('cep', models.CharField(max_length=9)),
                ('logradouro', models.CharField(blank=True, max_length=200)),
                ('numero_endereco', models.CharField(blank=True, max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CEL', 'Celular'), ('COM', 'Comercial'), ('RES', 'Residencial')], max_length=3)),
                ('ddd', models.CharField(max_length=2)),
                ('numero', models.CharField(max_length=15)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='clientes.cliente')),
            ],
        ),
    ]
