# Generated by Django 5.2.5 on 2025-09-22 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(help_text='Ex: E-mail Principal do Sistema', max_length=100)),
                ('email_host', models.CharField(max_length=100, verbose_name='Servidor SMTP (Ex: smtp.gmail.com)')),
                ('email_port', models.PositiveIntegerField(default=587, verbose_name='Porta')),
                ('email_host_user', models.EmailField(max_length=254, verbose_name='Usuário (e-mail de envio)')),
                ('email_host_password', models.CharField(max_length=100, verbose_name='Senha (ou Senha de App do Google)')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='Usar TLS')),
                ('ativo', models.BooleanField(default=False, help_text='Apenas UMA configuração pode estar ativa para notificações automáticas.')),
            ],
            options={
                'verbose_name': 'Configuração de Servidor de E-mail',
            },
        ),
        migrations.CreateModel(
            name='TemplateEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(help_text="Nome interno para identificar este template. Ex: 'Notificação de Avanço de Fase'", max_length=100, unique=True)),
                ('assunto', models.CharField(max_length=200)),
                ('tipo_conteudo', models.CharField(choices=[('texto', 'Texto Simples'), ('html', 'HTML')], default='html', max_length=5)),
                ('corpo', models.TextField(help_text='Use variáveis como {{ caso.id }}, {{ caso.titulo_caso }}, {{ cliente.nome_razao_social }}, {{ fase_origem.nome }}, {{ fase_destino.nome }}.', verbose_name='Corpo do E-mail')),
            ],
            options={
                'verbose_name': 'Template de E-mail',
                'verbose_name_plural': 'Templates de E-mail',
            },
        ),
        migrations.CreateModel(
            name='RegraNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatarios', models.TextField(help_text='Separe múltiplos e-mails por vírgula.')),
                ('fase_de_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_de_entrada', to='casos.faseworkflow', verbose_name='E entrar na Fase')),
                ('fase_de_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_de_saida', to='casos.faseworkflow', verbose_name='Quando sair da Fase')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casos.workflow', verbose_name='Para o Workflow')),
                ('template_email', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notificacoes.templateemail', verbose_name='Usar o Template de E-mail')),
            ],
            options={
                'verbose_name': 'Regra de Notificação',
                'verbose_name_plural': 'Regras de Notificação',
            },
        ),
    ]
