# Generated by Django 5.2.5 on 2025-08-24 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Analista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_aviso', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_sinistro', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_apolice', models.CharField(blank=True, max_length=50, null=True)),
                ('titulo_caso', models.CharField(max_length=200, verbose_name='Título do Caso')),
                ('segurado', models.CharField(blank=True, max_length=150)),
                ('terceiro', models.CharField(blank=True, max_length=150)),
                ('data_entrada', models.DateField(verbose_name='Data de Entrada')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_relatorio_preliminar', models.DateField(blank=True, null=True, verbose_name='Data Relatório Preliminar')),
                ('data_relatorio_final', models.DateField(blank=True, null=True, verbose_name='Data Relatório Final')),
                ('previsao_conclusao', models.DateField(blank=True, null=True, verbose_name='Previsão de Conclusão')),
                ('valor_causa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da Causa')),
                ('valor_prejuizo_apurado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Prejuízo Apurado')),
                ('prazo_regulacao_dias', models.IntegerField(blank=True, null=True, verbose_name='Prazo Regulação (Dias)')),
                ('horas_trabalhadas', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Horas Trabalhadas')),
                ('numero_caso_lo', models.CharField(blank=True, max_length=50, verbose_name='Número Caso LO')),
                ('resumo_caso', models.TextField(blank=True, verbose_name='Resumo do Caso')),
                ('observacao', models.TextField(blank=True)),
                ('advogado_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='casos.advogado', verbose_name='Advogado Responsável')),
                ('analista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='casos.analista')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casos', to='clientes.cliente')),
                ('cobertura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='casos.cobertura')),
                ('motivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='casos.motivo')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='casos.produto')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='casos.status')),
            ],
            options={
                'ordering': ['-data_entrada'],
            },
        ),
    ]
