# Generated by Django 5.2.5 on 2025-09-22 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaseWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['workflow', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='TipoTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Tipo de Tarefa')),
                ('prazo_dias', models.IntegerField(verbose_name='Prazo Padrão (em dias)')),
                ('tipo_prazo', models.CharField(choices=[('U', 'Dias Úteis'), ('C', 'Dias Corridos')], default='U', max_length=1, verbose_name='Tipo de Prazo')),
                ('recorrente', models.BooleanField(default=False, verbose_name='É uma tarefa recorrente?')),
            ],
            options={
                'verbose_name': 'Tipo de Tarefa',
                'verbose_name_plural': 'Tipos de Tarefa',
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Advogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Sistema')),
            ],
        ),
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_aviso', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_sinistro', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_apolice', models.CharField(blank=True, max_length=50, null=True)),
                ('titulo_caso', models.CharField(max_length=200, verbose_name='Título do Caso')),
                ('segurado', models.CharField(blank=True, max_length=150)),
                ('terceiro', models.CharField(blank=True, max_length=150)),
                ('data_entrada', models.DateField(verbose_name='Data de Entrada')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_relatorio_preliminar', models.DateField(blank=True, null=True, verbose_name='Data Relatório Preliminar')),
                ('data_relatorio_final', models.DateField(blank=True, null=True, verbose_name='Data Relatório Final')),
                ('previsao_conclusao', models.DateField(blank=True, null=True, verbose_name='Previsão de Conclusão')),
                ('valor_causa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da Causa')),
                ('valor_prejuizo_apurado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Prejuízo Apurado')),
                ('prazo_regulacao_dias', models.IntegerField(blank=True, null=True, verbose_name='Prazo Regulação (Dias)')),
                ('horas_trabalhadas', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Horas Trabalhadas')),
                ('numero_caso_lo', models.CharField(blank=True, max_length=50, verbose_name='Número Caso LO')),
                ('resumo_caso', models.TextField(blank=True, verbose_name='Resumo do Caso')),
                ('observacao', models.TextField(blank=True)),
                ('advogado_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='casos.advogado', verbose_name='Advogado Responsável')),
                ('analista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='casos.analista')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casos_do_cliente', to='clientes.cliente')),
                ('cobertura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='casos.cobertura')),
                ('fase_atual_workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='casos.faseworkflow', verbose_name='Fase Atual do Workflow')),
                ('motivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='casos.motivo')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='casos.produto')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='casos.status')),
            ],
            options={
                'ordering': ['-data_entrada'],
            },
        ),
        migrations.CreateModel(
            name='Andamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_andamento', models.DateField(verbose_name='Data do Andamento')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='andamentos', to='casos.caso')),
            ],
            options={
                'ordering': ['-data_andamento', '-data_cadastro'],
            },
        ),
        migrations.AddField(
            model_name='faseworkflow',
            name='atualiza_status_para',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='casos.status'),
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_execucao', models.DateField(verbose_name='Data de Execução')),
                ('tempo', models.DurationField(verbose_name='Tempo Gasto (HH:MM)')),
                ('descricao', models.TextField(verbose_name='Descrição da Atividade')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='casos.caso')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Profissional')),
            ],
            options={
                'ordering': ['-data_execucao'],
            },
        ),
        migrations.CreateModel(
            name='TarefaPadraoWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_padrao', to='casos.faseworkflow')),
                ('responsavel_override', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tipo_tarefa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='casos.tipotarefa')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Em Andamento'), ('C', 'Concluída')], default='P', max_length=1)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão Real')),
                ('observacao', models.TextField(blank=True)),
                ('descricao_conclusao', models.TextField(blank=True, verbose_name='Descrição da Conclusão')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='casos.caso')),
                ('origem_fase_workflow', models.ForeignKey(blank=True, help_text='Fase do workflow que gerou esta tarefa.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='casos.faseworkflow')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tipo_tarefa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='casos.tipotarefa', verbose_name='Tipo de Tarefa')),
            ],
            options={
                'ordering': ['data_criacao'],
            },
        ),
        migrations.AddField(
            model_name='faseworkflow',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases', to='casos.workflow'),
        ),
        migrations.CreateModel(
            name='RegraWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casos.produto')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casos.workflow')),
            ],
            options={
                'verbose_name': 'Regra de Workflow',
                'verbose_name_plural': 'Regras de Workflow',
                'unique_together': {('cliente', 'produto')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='faseworkflow',
            unique_together={('workflow', 'ordem')},
        ),
    ]
