# Generated by Django 5.2.5 on 2025-08-24 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0002_andamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Tipo de Tarefa')),
                ('prazo_dias', models.IntegerField(verbose_name='Prazo Padrão (em dias)')),
                ('tipo_prazo', models.CharField(choices=[('U', 'Dias Úteis'), ('C', 'Dias Corridos')], default='U', max_length=1, verbose_name='Tipo de Prazo')),
                ('recorrente', models.BooleanField(default=False, verbose_name='É uma tarefa recorrente?')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Em Andamento'), ('C', 'Concluída')], default='P', max_length=1)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão Real')),
                ('observacao', models.TextField(blank=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='casos.caso')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tipo_tarefa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='casos.tipotarefa', verbose_name='Tipo de Tarefa')),
            ],
            options={
                'ordering': ['data_criacao'],
            },
        ),
    ]
